---

# Canned ACL for files stored into S3. One of "private, public-read,
# public-read-write, authenticated-read, aws-exec-read, bucket-owner-read,
# bucket-owner-full-control"
acl: public-read

# Base URL for the uploaded files, either S3 download URL or CloudFront
# distribution URL to which the file path is appended for display in the
# interface
base_url: https://s3-eu-west-1.amazonaws.com/past3/

# Name of the Bucket used to store the files in. The bucket needs to be
# whitelisted for Cognito authenticated users
bucket: past3

# Id of the Cognito federated identity pool to be used to store users in
identity_pool_id: 'eu-west-1:8605f42e-f1e2-4c71-a796-a96ed9e79930'

# AWS region of the bucket
region: eu-west-1

# Client ID of the oAuth2 application created in the Google Cloud console
google_client_id: 693734536874-s0quna7oa2msnt1up4vubi4sh3uaucud.apps.googleusercontent.com
