---

# Default acl setting for new files: If set to true the files are created
# using `public-read` acl, if set to false they are created with `private` acl.
default_public: true

# Base URL for the uploaded files, either S3 download URL or CloudFront
# distribution URL to which the file path is appended for display in the
# interface
base_url: https://paste.luzifer.io/

# Theme name (lowercase) of Bootswatch.com theme (Optional, when not
# specified the original bootstrap theme is used)
bootswatch_theme: flatly

# Name of the Bucket used to store the files in. The bucket needs to be
# whitelisted for Cognito authenticated users
bucket: past3

# Client ID of the oAuth2 application created in the Google Cloud console
google_client_id: 693734536874-s0quna7oa2msnt1up4vubi4sh3uaucud.apps.googleusercontent.com

# Id of the Cognito federated identity pool to be used to store users in
identity_pool_id: 'eu-west-1:8605f42e-f1e2-4c71-a796-a96ed9e79930'

# AWS region of the bucket
region: eu-west-1

# Expiry in seconds set on pre-signed URLs for private files
# Minimum is 1s, maximum 604800s (seven days)
private_share_expiry: 900
